In [ ]:
import pandas as pd
import numpy as np
data=pd.read_csv("/heart.csv")
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
simple=SimpleImputer(strategy="mean",missing_values=np.nan)
simple.fit(data.iloc[:,4:6])
data.iloc[:,4:6]=simple.transform(data.iloc[:,4:6])

In [ ]:
from sklearn.impute import SimpleImputer
simple=SimpleImputer(strategy="mean",missing_values=np.nan)
simple.fit(data.iloc[:,8:9])
data.iloc[:,8:9]=simple.transform(data.iloc[:,8:9])

In [ ]:
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data.iloc[:,2:3]=lb.fit_transform(data.iloc[:,2:3])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
data.iloc[:,-1,]=lb.fit_transform(data.iloc[:,-1,])

In [ ]:
#splitting the data into train and test
x=data.iloc[:,1:-1]
x

sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0       1   0       125   212    0        1      168      0      1.0      2   
1       1   0       140   203    1        0      155      1      3.1      0   
2       1   0       145   174    0        1      125      1      2.6      0   
3       1   0       148   203    0        1      161      0      0.0      2   
4       0   0       138   294    1        1      106      0      1.9      1   
...   ...  ..       ...   ...  ...      ...      ...    ...      ...    ...   
1020    1   1       140   221    0        1      164      1      0.0      2   
1021    1   0       125   258    0        0      141      1      2.8      1   
1022    1   0       110   275    0        0      118      1      1.0      1   
1023    0   0       110   254    0        0      159      0      0.0      2   
1024    1   0       120   188    0        1      113      0      1.4      1   

      ca  thal  
0      2     3  
1      0     3  
2      0     3  
3      1     3  
4      3     2  
...   ..   ...  
1020   0     2  
1021   1     3  
1022   1     2  
1023   0     2  
1024   1     3  

[1025 rows x 12 columns]

In [ ]:
y=data.iloc[:,-1:]
y

target
0          0
1          0
2          0
3          0
4          0
...      ...
1020       1
1021       0
1022       0
1023       1
1024       0

[1025 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
x_train,y_train

(      sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
 315     1   3       148   244    0        0      178      0      0.8      2   
 204     0   2       146   278    0        0      152      0      0.0      1   
 363     1   2       130   246    1        0      173      0      0.0      2   
 5       0   0       100   248    0        0      122      0      1.0      1   
 1017    1   0       123   282    0        1       95      1      2.0      1   
 ...   ...  ..       ...   ...  ...      ...      ...    ...      ...    ...   
 835     1   2       118   149    0        0      126      0      0.8      2   
 192     0   2       115   564    0        0      160      0      1.6      1   
 629     1   3       138   282    1        0      174      0      1.4      1   
 559     1   0       120   237    0        1       71      0      1.0      1   
 684     1   2       140   185    0        0      155      0      3.0      1   
 
       ca  thal  
 315    2     2  
 2

In [ ]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1])

In [ ]:
from sklearn.metrics import r2_score,confusion_matrix,classification_report,accuracy_score
r2_score(y_pred,y_test)

0.439124487004104

In [ ]:
print(accuracy_score(y_pred,y_test))

0.8634146341463415


In [ ]:
confusion_matrix(y_pred,y_test)

array([[78,  8],
       [20, 99]])

In [ ]:
acc=(21+30)/(21+4+6+30)
acc

0.8360655737704918

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85        86
           1       0.93      0.83      0.88       119

    accuracy                           0.86       205
   macro avg       0.86      0.87      0.86       205
weighted avg       0.87      0.86      0.86       205



In [ ]:
#using the K-fold validation
from sklearn.model_selection import cross_val_score
accur=cross_val_score(estimator=lr,X=x_train,y=y_train,cv=15)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel

In [ ]:
print("Accuracy {:.2f}%".format(accur.mean()*100))

Accuracy 84.99%


In [ ]:
print("Standard Deviation:{:.2f}%".format(accur.std()*100))

Standard Deviation:4.94%


In [ ]:
#grid search
from sklearn.model_selection import GridSearchCV
parameters=[{'C':[0.25,0.5,0.75,1]}]
grid_search=GridSearchCV(estimator=lr,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
grid_search.fit(x_train,y_train)
best_accuracy=grid_search.best_score_
best_parameters=grid_search.best_params_
print("Best Accuarcy:{:.2f}%".format(best_accuracy*100))
print("Best parameters:",best_parameters)

Best Accuarcy:85.12%
Best parameters: {'C': 1}


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
#Support Vector machine
from sklearn.svm import SVC
class2=SVC(kernel="poly")
class2.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='poly')

In [ ]:
y_pred2=class2.predict(x_test)
y_pred2

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0])

In [ ]:
from sklearn.model_selection import cross_val_score
accuracy2=cross_val_score(estimator=class2,X=x_train,y=y_train,cv=10)
print("Accuracy of SVM:{:.2f}%".format(accuracy2.mean()*100))
print("Strandard Deviation of SvM:{:.2f}%".format(accuracy2.std()*100))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

Accuracy of SVM:69.63%
Strandard Deviation of SvM:4.51%


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters2=[{"C":[0.25,0.5,0.75,1],'kernel':['rbf','linear']}]
grid_search2=GridSearchCV(estimator=class2,param_grid=parameters2,scoring="accuracy",cv=10,n_jobs=-1)
grid_search2.fit(x_train,y_train)
best_accuracy=grid_search2.best_score_
best_parameters=grid_search2.best_params_
print("best_accuracy of svm :{:.2f}%".format(best_accuracy*100))
print("best parameters of svm:",best_parameters)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


best_accuracy of svm :83.17%
best parameters of svm: {'C': 0.25, 'kernel': 'linear'}


In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred2,y_test))

0.7560975609756098


In [ ]:
print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

           0       0.72      0.76      0.74        94
           1       0.79      0.76      0.77       111

    accuracy                           0.76       205
   macro avg       0.75      0.76      0.76       205
weighted avg       0.76      0.76      0.76       205



In [ ]:
#Decision tree
from sklearn.tree import DecisionTreeClassifier
class3=DecisionTreeClassifier()
class3.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred3=class3.predict(x_test)
y_pred3

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1])

In [ ]:
#k fold classifier
from sklearn.model_selection import cross_val_score
accuracy3=cross_val_score(estimator=class3,X=x_train,y=y_train,cv=10)
print("Accuracy of decision tree {:.2f}%".format(accuracy3.mean()*100))
print("Strandard deviation of decision tree {:.2f}%".format(accuracy3.std()*100))

Accuracy of decision tree 98.66%
Strandard deviation of decision tree 2.58%


In [ ]:
#grid search CV
from sklearn.model_selection import GridSearchCV
parameter3=[{"criterion":['gini','entropy','log_loss']}]
grid_search3=GridSearchCV(estimator=class3,param_grid=parameter3,scoring="accuracy",cv=10,n_jobs=-1)
grid_search3.fit(x_train,y_train)
best_accuracy=grid_search3.best_score_
best_parameters=grid_search3.best_params_
print("Best Accuracy of decision tree {:.2f}%".format(best_accuracy*100))
print("Best paramters:",best_parameters)

Best Accuracy of decision tree 99.02%
Best paramters: {'criterion': 'entropy'}


In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_pred3,y_test))

1.0


In [ ]:
print(classification_report(y_pred3,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        98
           1       1.00      1.00      1.00       107

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



In [ ]:
#Randomforest
from sklearn.ensemble import RandomForestClassifier
class4=RandomForestClassifier(n_estimators=100)
class4.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [ ]:
y_pred4=class4.predict(x_test)
y_pred4

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1])

In [ ]:
from sklearn.model_selection import cross_val_score
accuracy4=cross_val_score(estimator=class4,X=x_train,y=y_train,cv=10)
print("Accuracy of random forest {:.2f}%".format(accuracy4.mean()*100))
print("strandard deviation of randomforest {:.2f}%".format(accuracy4.std()*100))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example usi

Accuracy of random forest 99.27%
strandard deviation of randomforest 1.83%


In [ ]:
#grid search CV
from sklearn.model_selection import GridSearchCV
parameters=[{"criterion":['gini','entropy','log_loss'],"n_estimators":[100]}]
grid_search4=GridSearchCV(estimator=class4,param_grid=parameters,scoring="accuracy",cv=10,n_jobs=-1)
grid_search4.fit(x_train,y_train)
best_accuracy=grid_search4.best_score_
best_parameters=grid_search4.best_params_
print("Best Accuracy of random forest {:.2f}%".format(best_accuracy*100))
print("Best parameters of random forest ",best_parameters)

Best Accuracy of random forest 99.27%
Best parameters of random forest  {'criterion': 'entropy', 'n_estimators': 100}


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [ ]:
print(accuracy_score(y_pred4,y_test))

1.0


In [ ]:
print(classification_report(y_pred4,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        98
           1       1.00      1.00      1.00       107

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



In [ ]:
#XG boost classifier
import xgboost as xgb
class5=xgb.XGBClassifier()
class5.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred5=class5.predict(x_test)
y_pred5

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1])

In [ ]:
# k fold validation
from sklearn.model_selection import cross_val_score
accuracy5=cross_val_score(estimator=class5,X=x_train,y=y_train,cv=10)
print("Accuracy of xgboost {:.2f}%".format(accuracy5.mean()*100))
print("Strandard deviation of xgboost {:.2f}%".format(accuracy5.std()*100))

Accuracy of xgboost 99.02%
Strandard deviation of xgboost 2.17%


In [ ]:
#grid search cv
from sklearn.model_selection import GridSearchCV
parameters=[{"booster":["gbtree",'gblinear','dart'],'gamma':[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]}]
grid_search5=GridSearchCV(estimator=class5,param_grid=parameters,scoring='accuracy',cv=10,n_jobs=-1)
grid_search5.fit(x_train,y_train)
best_accuracy=grid_search5.best_score_
best_parameters=grid_search5.best_params_
print("Best Accuracy of xgboost {:.2f}%".format(best_accuracy*100))
print("best parameter of xgboost:",best_parameters)

Best Accuracy of xgboost 99.63%
best parameter of xgboost: {'booster': 'gbtree', 'gamma': 0.1}


In [ ]:
print(accuracy_score(y_pred5,y_test))

1.0


In [ ]:
print(classification_report(y_pred5,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        98
           1       1.00      1.00      1.00       107

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_pred5,y_test))

[[ 98   0]
 [  0 107]]


In [ ]:
# Tuning the logistic regression for the best parameter
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=0.25)
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=0.25)

In [ ]:
y_pred=lr.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1])

In [ ]:
print(accuracy_score(y_pred,y_test))

0.8634146341463415


In [ ]:
#tuning the best parameter for the SVM
from sklearn.svm import SVC
class2=SVC(C=0.75,kernel='linear')
class2.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.75, kernel='linear')

In [ ]:
y_pred2=class2.predict(x_test)

In [ ]:
accuracy_score(y_pred2,y_test)

0.8536585365853658

In [ ]:
#tuning the best parameter for the decision tree classifier
from sklearn.tree import DecisionTreeClassifier
class3=DecisionTreeClassifier(criterion='gini')
class3.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred3=class3.predict(x_test)

In [ ]:
accuracy_score(y_pred3,y_test)

1.0

In [ ]:
#tuning the parameter for the random forest
from sklearn.ensemble import RandomForestClassifier
class4=RandomForestClassifier(criterion='log_loss',n_estimators=100)
class4.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(criterion='log_loss')

In [ ]:
y_pred4=class4.predict(x_test)

In [ ]:
accuracy_score(y_pred4,y_test)

1.0

In [ ]:
from xgboost.sklearn import XGBClassifier
#tuning the xgboost for the best parameter
import xgboost as xgb
class5=XGBClassifier(booster='gbtree',gamma=0.2)
class5.fit(x_train,y_train)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=0.2, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred5=class5.predict(x_test)

In [ ]:
accuracy_score(y_pred5,y_test)

1.0

In [ ]:
pip install gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.1/57.1 MB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.1/320.1 kB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 64.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 9.8 MB/s eta 0:00:00
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2


In [ ]:
import gradio as gr

In [ ]:
def greet(name):
  return 'Hello '+name+' !'
demo=gr.Interface(fn=greet,
                  inputs=gr.Textbox(lines=2,placeholder="Enter Name"),outputs="text")
demo.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://7cb7020afacdea6599.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
def greet(name,is_morning,temperature):
  saluation="Good morning" if is_morning else "good evening"
  greeting=f"{saluation}{name}.Its {temperature} is in the morning"
  celsius=(temperature-32)*5/9
  return greeting,round(celsius,2)
demo=gr.Interface(fn=greet,
                  inputs=["text","checkbox",gr.Slider(0,100)],
                  outputs=["text","number"])
demo.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://359c7d5d02e70872a2.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
import gradio as gr
import warnings
warnings.filterwarnings("ignore")

In [ ]:
def Heartdisease_classification(age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca):
    x = np.array([age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca],dtype=float)
    prediction =  class4.predict(x.reshape(1,-1))
    if prediction[0] == [1] :
        prediction = 'Heart disease'
    else:
        prediction ='No heart disease'
    return prediction
heartdisease_classification = gr.Interface(fn=Heartdisease_classification,
                                         inputs=["number","number","number","number","number","number","number","number","number","number","number","number"],
                                         outputs=gr.Textbox(),
                                         description='Heart Disease Prediction')

In [ ]:
heartdisease_classification.launch(share = True,debug=True)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://a70d8fbbd099647ef1.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
